############# Dutch navigation ##############

# main menu
[[main]]
identifier = "home"
name = "Home"
url = "/nl/"
weight = 100

[[main]]
identifier = "services"
name = "Diensten"
url = "/nl/#services"
weight = 200

[[main]]
identifier = "about"
name = "Over ons"
url = "/nl/#about"
weight = 300

[[main]]
identifier = "projects"
name = "Projecten"
url = "/nl/projects"
weight = 250

[[main]]
identifier = "contact"
name = "Contact"
url = "/nl/#contact"
weight = 400

[[footer]]
identifier = "legal"
name = "Juridische informatie"
url = "legal"
weight = 100
